# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_letter', models.CharField(max_length=1)),
                ('data_array', models.CharField(max_length=500)),
            ],
        ),
    ]
